name: Build Telegram API Server
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:  
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Install Dependencies
    #   run: sudo apt update && sudo apt-get install zip libssl-dev zlib1g-dev g++ gperf cmake

    - name: Build
      run: |
        git clone --recursive https://github.com/tdlib/telegram-bot-api.git
        cd telegram-bot-api
        mkdir build
        cd build
        touch telegram-bot-api
        # cmake -DCMAKE_BUILD_TYPE=Release ..
        # cmake --build .
        zip telegram-bot-api.zip telegram-bot-api

    - name: Rename and Move files to root
      run: |
        mv telegram-bot-api TelegramBotAPI

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add TelegramBotAPI TelegramBotAPI/build/telegram-bot-api TelegramBotAPI/build/telegram-bot-api.zip
        git commit -m "Update output from movieindex.py"
        git push
